### ISSUE TITLE
[Enhancement] Copying images and remaining elements

### ISSUE THREAD

**Issue by pidgeon777** [MariusEvans/docxCopier#1]
Hello, how could it be possible to copy even images or bullet points, etc., with your script?

**Comment by MariusEvans** [comment]
Hi, sorry for such a late reply! I've tried doing this but unfortunately I could not get the feature to work with the python library I used. I may see if this is possible in the future though. Thanks for leaving the suggestion.

**Comment by pidgeon777** [comment]
No problem, this would be a valuable feature to add, let's hope in the future it will be a possible thing to implement.
